version: '3.9'

services:
  frontend:
    build: .
    image: doctor-dashboard:latest 
    container_name: scd-doctor-dashboard
    ports:
      - "4002:3000"
    env_file:
      - .env
    restart: always
